[package]
name = "itch5"
author = "zjom"
description = "Parser for Nasdaq TotalView-ITCH 5.0"
license = "Unlicense"
version = "0.1.4"
edition = "2024"

[dependencies]
zerocopy = { version = "0.8", features = ["derive"] }


[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
memmap2 = "0.9.10"


[[bench]]
name = "itch_bench"
harness = false
