[package]
name = "app"
version = "0.1.0"
edition = "2024"
description = "High frequency trading in Rust"
license = "Unlicense"
readme = "README.md"

[dependencies]
moldudp = {path = "../moldudp"}
itch5 = {path = "../itch5", features = ["chrono"]}
orderbook = {path = "../orderbook"}
memmap2 = "0.9.10"
rand = "0.10.1"
anyhow = "1.0.102"
env_logger = "0.11.10"
log = "0.4.29"
ctrlc = "3.5.2"
clap = {version="4.6.1", features=["derive"]}

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["html_reports", "cargo_bench_support"] }
crossbeam = "0.8.4"
socket2 = "0.6"

[[bench]]
name = "end_to_end"
harness = false
